version: "3"
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/collegepedia
      - public-data:/collegepedia/public
      - tmp-data:/collegepedia/tmp
      - log-data:/collegepedia/log
    networks:
      - collegepedia-network
# =======開発と本番切り替え====================
  #   depends_on:
  #     - db

  # db:
  #   image: postgres
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  #   environment:
  #     - "POSTGRES_USER=postgres"
  #     - "POSTGRES_PASSWORD=password"
  #   networks:
  #     - collegepedia-network
# =========================================

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/collegepedia/public
      - tmp-data:/collegepedia/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - collegepedia-network
    tty: true
    stdin_open: true
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  collegepedia-network:
    external: true
